"""Add user id to order table

Revision ID: b03648d80c77
Revises: cf6a8fb1fd44
Create Date: 2025-07-25 21:45:57.032669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03648d80c77'
down_revision = 'cf6a8fb1fd44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
